name: StatisticsUpdater
version: 1.0.0
main: com.hellominers.statisticsupdater.StatisticsUpdater
description: Runs the DFU on all outdated statistics files, with additional migration for pre-flattening item/block ids.
author: Aya
api-version: '1.20'
load: STARTUP